query getMyLikeBlogList(
$language: String!
$tag_code: Int
$order_type: Int
$limit: Int
$offset: Int
) {
	getMyLikeBlogList(
	language: $language
	tag_code: $tag_code
	order_type: $order_type
	limit: $limit
	offset: $offset
	) {
		result
		count
		blog {
			code
			updated_at
			created_at
			images {
				code
				origin_path
				url
			}
			tags {
				code
				type
				translations {
					name
					language
				}
			}
			blog_tags {
				code
				type
				country_code
				name
				language
			}
			translations {
				updated_at
				created_at
				code
				title
				sub_title
				description
				content
				language
			}
			writer {
				email
				name
				picture
				nickname
				introduce
			}
			like_members {
				id
				email
				name
				nickname
			}
		}
	}
}
