query getSpotDetail($code: Int!, $languages: [String]) {
  getSpotDetail(code: $code) {
    result
    spot {
      code
      latitude
      longitude
      address
      is_local_write
      telephone
      is_reservable
      opening_hours
      is_confirm
      view_count
      is_publish
      like_count
      review_total_score
      rating_review_count
      no_rating_review_count
      share_count
      created_at
      updated_at

      images {
        code
        blog_code
        main_image
        origin_path
        url
      }

      options {
        code
        p_code
        spot_code
        name
        information
        images {
          main_image
          origin_path
          url
        }
        price
        discount_price
        is_reserve
        is_dropdown
        is_require_payment
        refund_data
        fees
        settlement_price
      }
      blogs {
        code
        member_code
        view_count
        like_count
        review_count
        share_count
        is_publish
        mobile_image_path
        is_recommend
        created_at
        updated_at
        images {
          code
          origin_path
          url
        }
        translations(languages: $languages) {
          code
          blog_code
          title
          sub_title
          description
          content
          language
          is_publish
          is_default
          created_at
          updated_at
        }
      }

      translations(languages: $languages) {
        code
        is_default
        spot_code
        spot_name
        spot_search_title
        is_publish
        title_price
        price
        language
        more_infomation
        precautions
      }
      register {
        code
        id
        email
        name
        nickname
        level
        picture
      }
      tags {
        code
        type
        country_code
        translations(languages: $languages) {
          name
          language
        }
      }

      like
      images {
        main_image
        origin_path
        url
      }
      reserve_info {
        code
        delivery_fee
        spot_code
        notice_email
        min_order_amount
        type
        is_require_date
        is_require_time
        outside_url
        additional_reservation_infos {
          code
          created_at
          updated_at
          translations {
            code
            language
            header
            description
            created_at
            updated_at
          }
        }
        is_require_payment
        is_require_confirm
        is_require_day
        refund_percents
        limit_payment_second
        reserve_hours
        min_order_count
        max_order_count
        is_active
        time_unit
        reserve_limit_date
        remarks
        time_unit
        reserve_limit_date
      }
    }
  }
}
